package com.example.dickysuryo.testdicoding.Constant;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;

public class Constant {

    String[] gundam1 = {"GUNDAM SAZABI","https://ci6.googleusercontent.com/proxy/Obix5ltAjaW-nVKEN9MBJ1pZv_Z6tcGA5njdUVKCLLnOZirucBXWokUKIcdkzDeA5M1DyF78H_GsroD2xqLSv2KhNku5Vk_gDDnyRFwnmSiJ0QkeenAiXg2v=s0-d-e1-ft#https://i.pinimg.com/474x/ef/fb/ea/effbeaaa1a2132b2c4260f1b47410246.jpg","The beam shot rifle is a hand-carried ranged beam weapon that was designed to be used by the Sazabi. It is noticeably larger than most other beam rifles, is powered by a rechargeable energy cap, and has a power rating of 10.2 MW."};
    String[] gundam2 = {"GUNDAM STRIKE FREEDOM","https://ci5.googleusercontent.com/proxy/c347srfOCaOugBmB1OXBKxEXXXFWnOuQPn6Zfb-67WJIhwsp-5m1JYdUhXSyTaJJmakJwW_OGJIMbGo8R4JbuX3-TRtZ82OG5UXr5B6l8VHisFP-F_lBJDBX=s0-d-e1-ft#https://i.pinimg.com/474x/ef/76/58/ef76589047d22198221544a8094e0bc0.jpg","Strike Freedom Gundam. ZGMF-X20A Strike Freedom Gundam is the direct successor to the Freedom Gundam that is given to Kira after the original's destruction. While similar in looks and armed with a similar METEOR system, its performance outshines many other Mobile Suits on the battlefield."};
    String[] gundam3 = {"GUNDAM STRIKE FREEDOM V2","https://ci3.googleusercontent.com/proxy/KyF594kqbqkiEDXUjqidH-et3PKPTRu2iXE0FxYl7OtJ7_U-122vOPbQTaoTXIcXruLIxQ9SWfaqD-0hsi_L0o4dTA2YhuJN3sRBALxmE_KYe2cKO-AoHz3r=s0-d-e1-ft#https://i.pinimg.com/474x/3b/e3/e4/3be3e476279f7569872ed3efac3b548e.jpg","Kira Yamato's Strike Freedom from the \"Gundam Seed Destiny\" TV series comes with its full load of armaments including dual rifles that can combine, beam sabers that connect at ends, rail guns, chest cannon, and detachable Super DRAGOON wings. Display base included."};
    String[] gundam4 = {"GUNDAM SEED ","https://ci3.googleusercontent.com/proxy/Nym2JX1vlAY6md_VQ-14hREw3GHK38cEYNo4OKcDmrgNZVtGHqH4PuY4b3HvIslkxDmavheMmpma5TZoWCZoioqhoO9joLRNrdFaZfPeTUTOZj6ixAjgaT3E=s0-d-e1-ft#https://i.pinimg.com/474x/ea/27/0a/ea270a1e39d517ddc663eb617f2bb1f5.jpg","Kidō Senshi Gandamu Shīdo) is an anime series developed by Sunrise and directed by Mitsuo Fukuda. The ninth installment in the Gundam franchise, Gundam SEED takes place in a future calendar era, in this case the Cosmic Era, the first to do so. In this era, mankind has developed into two subspecies: Naturals, who reside on Earth, and Coordinators, genetically enhanced humans capable of amazing feats of intellect who emigrate to man-made orbital colonies to escape persecution by natural humans. The story revolves around a young Coordinator Kira Yamato who becomes involved in the war between the two races after a third, neutral faction's space colony is invaded by the Coordinators."};
    String[] gundam5 = {"GUNDAM EXIA","https://ci6.googleusercontent.com/proxy/dMgNGV_PpHUHgh5ndIxKStdL7_ZcuBu7yTnbYvp0ETSyrZBUV610bJ4Dw3Ph7dnyPMjbBUuicnIlhDf0fSsLN5lu4q6jQKd2dPHWwlwkrt_-NuqotYFi419r=s0-d-e1-ft#https://i.pinimg.com/474x/56/e6/e6/56e6e6dc67bc80e9c66a23fe0b796182.jpg","Named GN Power Lines (also known as GN Cables), their main purpose is to transport large amounts of GN Particles to and from various parts of the body. As Exia frequently engages the enemy in close quarters, its higher amount of exposed cables allows it to have finer posture control than the other Gundams."};
    String[] gundam6 = {"GUNDAM DESTINY","https://ci4.googleusercontent.com/proxy/4sfMpJtwRrOJqo0gawtuTdAbP7RncLFrCbueseYZrf329qVEzTwrWdtP-i_RHvl1BKKKVHVH2WbC5spTUi_tcR66_M3PlYpJLYyE4trMmnOIgcWTWumHMfEb=s0-d-e1-ft#https://i.pinimg.com/474x/8c/99/ce/8c99cea42a6811540ac668b7da7ca263.jpg","For close combat, it has two beam boomerangs that double as beam sabers, a pair of palm beam cannons, and a large beam sword. For ranged battle, it is equipped with a long-range beam cannon and a beam rifle. For defense, it mounts a small physical shield as well as two beam shield generators."};
    String[] gundam7 = {"GUNDAM WING","https://ci6.googleusercontent.com/proxy/KZ_wod4Ik5z0Tew3eq11A6ZpkEfuN2UHMR_MXhX33efrMZ6EDFcFcKqHhgyBt86N3Jh2PUE843n3znL4OIeFEawIqlTonhiuEDIh1FLKJL8_sVrX50Ux09a5=s0-d-e1-ft#https://i.pinimg.com/474x/6b/14/d6/6b14d6c503915cf4347d08d2bad87509.jpg","The colonies wishing to be free, join together in a movement headed by the pacifist Heero Yuy. ... The series focuses primarily on the five Gundam pilots: Heero Yuy (an alias, not to be confused with the martyred pacifist), Duo Maxwell, Trowa Barton, Quatre Raberba Winner and Chang Wufei."};
    String[] gundam8 = {"GUNDAM BARBATOS CUSTOM WHITE","https://ci4.googleusercontent.com/proxy/S99-xAPxOIGipoOysGXF2XDOJqxP-iqm3Mykn6nIXQE-BCkYgQCdw0Im4xvzPOVwDpaf-_Jm-zRNUlXMYbKWz9zo7iZQ5D0YQ1livnheKxh-GiFzHC7F9A17DxNC=s0-d-e1-ft#https://i.pinimg.com/400x300/b4/2b/39/b42b3901e0f9f21f3a552ebe70151e9c.jpg","The Gundam Barbatos is the 8th of the 72 Gundam Frames created by Gjallarhorn near the end of the Calamity War to counter the threat of the powerful mobile armors such as Hashmal. It was later discovered by Maruba Arkay in the Mars desert and was recovered to serve as a power reactor for Chryse Guard Security's base."};
    String[] gundam9 = {"GUNDAM THUNDERBOLT","https://i.pinimg.com/originals/8f/df/c7/8fdfc7d642b7b55fd8c0298eb8147ede.jpg","Universal Century 0079. Federation troops and Zeon forces carry out a fierce battle in the \"Thunderbolt Sector\" in what was once Side 4 \"Moore\". The \"Thunderbolt Sector\" is a shoal zone composed of the debris of destroyed space colonies, named for the electrical discharges from the metal debris."};
    String[] gundam10= {"GUNDAM MK II","https://2.bp.blogspot.com/-TVdDamMrqiM/U4u2Eq197SI/AAAAAAADGuc/o3ZKOaDF_qA/s1600/IMG_0006.JPG","The modular Gundam Mk. II (in RX-78-esque AEUG colors) is a conservative, no-frills design in Zeta Gundam. The FXA-05D G-Defenser provides the Super Gundam with much needed upgrades to offense and defense. The RX-178 Gundam Mark-II is a fictional mobile suit from the Universal Century Gundam anime series."};

    public final ArrayList arrayTitle = new ArrayList<>(Arrays.asList(gundam1[0],gundam2[0],gundam3[0],gundam4[0],gundam5[0],gundam6[0],gundam7[0],gundam8[0],gundam9[0],gundam10[0]));
    public final ArrayList arrayImage = new ArrayList<>(Arrays.asList(gundam1[1],gundam2[1],gundam3[1],gundam4[1],gundam5[1],gundam6[1],gundam7[1],gundam8[1],gundam9[1],gundam10[1]));
    public final ArrayList arrayDescription = new ArrayList<>(Arrays.asList(gundam1[2],gundam2[2],gundam3[2],gundam4[2],gundam5[2],gundam6[2],gundam7[2],gundam8[2],gundam9[2],gundam10[2]));


}
